version: '3.4'
services:

  gestion-station-ski-image:
    build: .
    ports:
      - 8089:8089
    image: chamesebh/gestion-station-ski
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/stationSki?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=
    depends_on:
      - db-mysql

  db-mysql:
    image: mysql:5.7
    container_name: mysql_new
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationSki
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:





